services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ${PATH_TO_DIR}/app:/app/app
    container_name: papernest-address-api
    env_file:
      - .env
    ports:
      - "8005:80"